comment out checks for shared libraries in atlas 3.8.4 apart from check for libatlas.so
Change-Id: I6040e9516d54d3bbd0000b3e4b95bb44ba617110
Reviewed-on: https://marduk.tchpc.tcd.ie:8443/267
Reviewed-by: <darach@tchpc.tcd.ie>
Tested-by: <darach@tchpc.tcd.ie>

diff --git a/packages/atlas/3.8.4/Makefile b/packages/atlas/3.8.4/Makefile
--- a/packages/atlas/3.8.4/Makefile
+++ b/packages/atlas/3.8.4/Makefile
@@ -98,15 +98,15 @@ do-build:
 	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libatlas.so -o \
 	     ! -f  $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libatlas.so ]; \
 	       then echo "libatlas shared lib missing"; exit 1; fi; 
-	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libcblas.so -o \
-	     ! -f  $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libcblas.so ]; \
-	       then echo "libcblas shared lib missing"; exit 1; fi; 
-	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libf77blas.so -o \
-	     ! -f  $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libf77blas.so ]; \
-	       then echo "libf77blas shared lib missing"; exit 1; fi; \
-	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/liblapack.so -o \
-	     ! -f $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/liblapack.so ]; \
-	       then echo "liblapack shared lib missing"; exit 1; fi; 
+#	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libcblas.so -o \
+#	     ! -f  $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libcblas.so ]; \
+#	       then echo "libcblas shared lib missing"; exit 1; fi; 
+#	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libf77blas.so -o \
+#	     ! -f  $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/libf77blas.so ]; \
+#	       then echo "libf77blas shared lib missing"; exit 1; fi; \
+#	if [ ! -e $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/liblapack.so -o \
+#	     ! -f $(WORKDIR)/ATLAS-build-$(SYSTEM_TYPE)/lib/liblapack.so ]; \
+#	       then echo "liblapack shared lib missing"; exit 1; fi; 
 
 do-test:
 	$(MODULE_ADD) $(BUILD_DEPENDS);   \
